FROM openjdk:11

# 작업 디렉토리 설정
WORKDIR ./

CMD ["ls", "-al"]

# Gradle 빌드
#RUN chmod +x ./gradlew && ./gradlew clean build

#ARG JAR_FILE=./build/libs/o2o-0.0.1-SNAPSHOT.jar
#COPY ${JAR_FILE} ./app.jar
#ENV TZ=Asia/Seoul
#ENTRYPOINT ["java", "-jar", "./app.jar"]
